### ISSUE TITLE
Please enter a valid domain name - potential issue

### ISSUE THREAD

**Issue by schimpy** [ail-project/ail-typo-website#4]
Hello team, 

I tried to run typosquatting-finder.circl.lu with the domain nn.sk but I got the error code "Please enter a valid domain name". As this is a valid domain, I assume there might be an issue with the input filtering. Any updates on this?

**Comment by DavidCruciani** [comment]
Hi @schimpy ,

It's effectively an issue i saw last days, it will be fix very soon. I will close this issue when the push will be done.

Thanks a lot for your feedback.

**Comment by DavidCruciani** [comment]
Hi @schimpy ,

The public instance is up to date now and running with some update. The limitation is removed and just check serve-side if the domain is valid.

Thanks again for the report you did and don't hesitate to give us a feedback or to report other issues.
