### ISSUE TITLE
Sharing results gives application localhost address

### ISSUE THREAD

**Issue by Moustrash** [ail-project/ail-typo-website#5]
Hello,
The "Share" button copies a local address to the clipboard instead of the hostname of the application : http://localhost:7005/eae0cc3c-04ae-465d-8ade-a25abe3daf12 (expected https://typosquatting-finder.circl.lu/eae0cc3c-04ae-465d-8ade-a25abe3daf12).
![image](https://user-images.githubusercontent.com/43669462/200784965-52ea0811-3490-4b2e-aef1-8273975bc39c.png)

The path is correct though, so it is possible to use it to share the result.
Regards

**Comment by DavidCruciani** [comment]
HI @Moustrash,

This is a commit error from my side. I fixed it in my last commit and will be fix on the public instance soon.

Thanks for your reporting !

**Comment by DavidCruciani** [comment]
Hi @Moustrash,

The public instance is up to date now and running with some update. The share option is now fix.

Thanks again for the report you did and don't hesitate to give us a feedback or to report other issues.
